### DISCUSSION TITLE
Welcome to MSBuild.SDK.SystemWeb Discussions!

### DISCUSSION THREAD

**Discussion by CZEMacLeod** [CZEMacLeod/MSBuild.SDK.SystemWeb#8] [General]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by slang25** [comment]
Hey, thank you for putting this package together, I've currently used it for a proof of concept and it's working great!

**Comment by Zonorai** [comment]
Hi, thank you for your work this project has really helped me with my current project, I was wondering if anyone has gotten this SDK or something similar to work on a Azure Web App? If I run just the templates for the SDK and try to push it to an azure web app via a Azure Pipeline using VSBuild I keep getting this 
_  
Transforming Source File: D:\a\1\s\Web.config;Web.config
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\Web\Microsoft.Web.Publishing.targets(1480,5): Error : Could not open Source file: Could not find file 'D:\a\1\s\Web.config;Web.config'.
_

So out of the box you can't run this against a pipeline and push it to azure after a few tries however and some modifications I did get a working pipeline and deploy, but the WebApp is not responding at all.
The property I added to the .csproj to get it working in the pipeline is `<AutoParameterizationWebConfigConnectionStrings>false</AutoParameterizationWebConfigConnectionStrings>`

If anyone can maybe help point me in the right direction I'd be more than happy to contribute a PR that fixes this, currently I just don't understand where to start, a lot of sources I read said that if the azure web app is not responding then it's a config issue.

Project runs perfectly on local IIS & IIS Express

**Reply by CZEMacLeod** [reply]
Hi @Zonorai 
I am glad it is helping you out.
I haven't tried this scenario specifically, perhaps you could set up a repo on GitHub to demonstrate the issue, and I think you should probably just open an issue for this.
I know there are some specific things around publishing that work and don't work.
I'm not sure exactly how you are publishing to azure web apps.
I tried the following and it managed to deploy locally correctly.
```cmd
mkdir test2
cd test2
dotnet new systemwebfull
msbuild
msbuild /t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="MyPublishDir"
MyPublishDir\test2.deploy.cmd /Y
```
If you use something like this in your azure pipeline
```yml
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArgs: '/t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\\"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
```
You should get the msdeploy files as artifacts which you can then use in a release pipeline to deploy.
I haven't tried your exact scenario, and there may be typos in my examples, above, but perhaps it will get you further.

There may be more help in the original thread on this - [Add support for ASP.NET (non-Core) projects
#2670](https://github.com/dotnet/project-system/issues/2670#issuecomment-761927390)

I do know that this is an area where more documentation is needed, especially when it comes to covering different scenarios.
